use_default_settings: true

general:
  instance_name: "AutoDL SearXNG"

search:
  safe_search: 0
  formats:
    - html
    - json

server:
  port: 8080
  bind_address: "0.0.0.0"
  secret_key: "autodl_searxng_secret_key"
  limiter: false
  public_instance: false
